name: Déployer l'application SvelteKit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Vérification du code source
        uses: actions/checkout@v3

      - name: Configuration de l'agent SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfert du projet vers le VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf ${{ secrets.VPS_DIR }} && mkdir -p ${{ secrets.VPS_DIR }}"
          scp -r ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DIR }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat > ${{ secrets.VPS_DIR }}/.env <<EOF
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }}
          EOF"

      - name: Installation des dépendances
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_DIR }} && npm install"

      - name: Construction de l'application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_DIR }} && npm run build"

      - name: Lancement de l'application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_DIR }} && pm2 restart smartdesk ||
          PORT=80 pm2 start ${{ secrets.VPS_DIR }}/build/index.js --name smartdesk"

      - name: Confirmation du déploiement
        run: echo "Déploiement terminé"
